name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download the ESMA version of .NET too
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: FactChecker
    - name: Build
      run: dotnet build --no-restore
      working-directory: FactChecker
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: XUnitTestProject

